### ISSUE TITLE
find: ./oauth2/static/js/

### ISSUE THREAD

**Issue by open-yuhaoz** [klinux/velero-dashboard#1]
Hello, make image command execution error cannot find js file, is there any problem with Dockerfile? The following is the log file
`(7/8) Installing nodejs (12.15.0-r1)
(8/8) Installing npm (12.15.0-r1)
Executing busybox-1.31.1-r9.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 64 MiB in 22 packages
/usr/bin/uglifyjs -> /usr/lib/node_modules/uglify-es/bin/uglifyjs
/usr/bin/uglifycss -> /usr/lib/node_modules/uglifycss/uglifycss
+ uglifycss@0.0.29
+ uglify-es@3.3.9
added 4 packages from 39 contributors in 2.565s
find: ./oauth2/static/js/: No such file or directory
The command '/bin/sh -c apk update &&     apk add npm &&     npm install -g uglifycss uglify-es &&     chown -R root: * &&     find ./oauth2/static/js/ -type f         -name "*.js" ! -name "*.min.*" ! -name "vfs_fonts*"         -exec echo {} \;         -exec uglifyjs -c -o {}.min {} \;         -exec rm {} \;         -exec mv {}.min {} \; &&     find ./oauth2/static/css/ -type f         -name "*.css" ! -name "*.min.*"         -exec echo {} \;         -exec uglifycss --output {}.min {} \;         -exec rm {} \;         -exec mv {}.min {} \; &&     find . -type d -name "__pycache__"         -prune -exec rm -rf {} \;' returned a non-zero code: 1
make: *** [image] 错误 1
`

**Comment by drummerglen** [comment]
> Hello, make image command execution error cannot find js file, is there any problem with Dockerfile? The following is the log file
> `(7/8) Installing nodejs (12.15.0-r1)
> (8/8) Installing npm (12.15.0-r1)
> Executing busybox-1.31.1-r9.trigger
> Executing ca-certificates-20191127-r2.trigger
> OK: 64 MiB in 22 packages
> /usr/bin/uglifyjs -> /usr/lib/node_modules/uglify-es/bin/uglifyjs
> /usr/bin/uglifycss -> /usr/lib/node_modules/uglifycss/uglifycss
> 
> * uglifycss@0.0.29
> * uglify-es@3.3.9
>   added 4 packages from 39 contributors in 2.565s
>   find: ./oauth2/static/js/: No such file or directory
>   The command '/bin/sh -c apk update &&     apk add npm &&     npm install -g uglifycss uglify-es &&     chown -R root: * &&     find ./oauth2/static/js/ -type f         -name "_.js" ! -name "_.min._" ! -name "vfs_fonts_"         -exec echo {} ;         -exec uglifyjs -c -o {}.min {} ;         -exec rm {} ;         -exec mv {}.min {} ; &&     find ./oauth2/static/css/ -type f         -name "_.css" ! -name "_.min.*"         -exec echo {} ;         -exec uglifycss --output {}.min {} ;         -exec rm {} ;         -exec mv {}.min {} ; &&     find . -type d -name "**pycache**"         -prune -exec rm -rf {} ;' returned a non-zero code: 1
>   make: *** [image] 错误 1
>   `
@open-yuhaoz 
Hi, did you fix it? I encounter the similar problem
