### ISSUE TITLE
Dashboard request failed 500

### ISSUE THREAD

**Issue by open-yuhaoz** [klinux/velero-dashboard#2]
![c89492efc964d6bd6f608424b226542](https://user-images.githubusercontent.com/30641603/102568952-8bca1380-411f-11eb-9c0c-6c0bd465db4d.png)

![image](https://user-images.githubusercontent.com/30641603/102569012-a43a2e00-411f-11eb-86d7-1b9ba03b07ec.png)

Hi, could you please tell me where the dashboard request is configured? My Velero is deployed in the official website. Could you please give me an answer?

**Comment by klinux** [comment]
> ![c89492efc964d6bd6f608424b226542](https://user-images.githubusercontent.com/30641603/102568952-8bca1380-411f-11eb-9c0c-6c0bd465db4d.png)
> 
> ![image](https://user-images.githubusercontent.com/30641603/102569012-a43a2e00-411f-11eb-86d7-1b9ba03b07ec.png)
> 
> Hi, could you please tell me where the dashboard request is configured? My Velero is deployed in the official website. Could you please give me an answer?

Hello, @open-yuhaoz 

I'm sorry, this dashboard it's not completed yet, exist a lot of work to do.

All requests is made by the file utils.py.

```
def velero(cmd):
    """
    Objetive: Run velero and get output json
    """
    run = os.popen(f"/usr/local/bin/velero {cmd} -o json")
    return json.loads(run.read())

def velero_str(cmd):
    """
    Objetive: Run velero and get output text
    """
    run = os.popen(f"/usr/local/bin/velero {cmd}")
    return run.read()
```

I have to implement the utilization in cluster, now, it utilize a config file in .kube/config home user.

But if you want to help you are welcome .

Thank you

**Comment by open-yuhaoz** [comment]
Hello, @klinux  we might be able to contact velero developers to do this and ask if they have opened the service interface.

**Comment by open-yuhaoz** [comment]
Hello, @klinux 
we might be able to contact velero developers to do this and ask if they have opened the service interface.

**Comment by klinux** [comment]
> Hello, @klinux
> we might be able to contact velero developers to do this and ask if they have opened the service interface.

Well, I've looking for some api, but it isn't provided, I think will never provided, because the nature of kubernetes crd's. But yes, We can try to talk to velero team.

**Comment by drummerglen** [comment]
HI,

Here is a temporary solution to resolve this issue.
And I have forked this repo for native kubernetes environment [https://github.com/drummerglen/velero-dashboard](url)

### **Step 1**
1. Download velero binary from official repo. [https://github.com/vmware-tanzu/velero/releases](url)
2. `unzip -q velero-v1.6.0-linux-amd64.tar.gz` to get the binary file `velero`.
3. copy `velero` to ./velero-dashboard/ where Makefile located.
4. create folder `/src/oauth2/static/js/ `and `/src/oauth2/static/css/ `manually.
### **Step 2**
4. Modify the Dockerfile to add velero binary file
```
FROM alpine:3.11 as build
ADD velero /usr/local/bin/         <-----------  add this line
WORKDIR /app
...
FROM python:alpine3.11 as prod
ADD velero /usr/local/bin/         <-----------  add this line
RUN apk update && \
```
5. Modify the Makefile for test
```
image: ## Build and push image
	docker build -t ${IMG}:latest -f ${DOCKER_DIR}/Dockerfile .    <------------  just retain this line
```
### **Step 3**
6. Enter into ./velero-dashboard
7. Commit command `make image`
8. After build image successfully use `docker images` to check it
9. Export the image to local `docker save -o velero-dashboard.tar klinux/velero-dashboard:latest`
    or push this image to your registry which kubernetes use.

### **Step 4**
10. Modify the deployment file to assgin a right `serviceAccount ` in /velero-dashboard/utils/kubernetes/velero-dashboard-dep.yaml
```
    spec:
      serviceAccount: velero          <-----------  add this line
      containers:
```
11. (optional) Modify the svc file to enable NodePort.
12. `kubectl apply -f .`
13. It works.

**Comment by klinux** [comment]
> HI,
> 
> Here is a temporary solution to resolve this issue.
> And I have forked this repo for native kubernetes environment [https://github.com/drummerglen/velero-dashboard](url)
> ### **Step 1**
> 
>     1. Download velero binary from official repo. [https://github.com/vmware-tanzu/velero/releases](url)
> 
>     2. `unzip -q velero-v1.6.0-linux-amd64.tar.gz` to get the binary file `velero`.
> 
>     3. copy `velero` to ./velero-dashboard/ where Makefile located.
> 
>     4. create folder `/src/oauth2/static/js/ `and `/src/oauth2/static/css/ `manually.
> 
> 
> ### **Step 2**
> 
>     1. Modify the Dockerfile to add velero binary file
> 
> 
> ```
> FROM alpine:3.11 as build
> ADD velero /usr/local/bin/         <-----------  add this line
> WORKDIR /app
> ...
> FROM python:alpine3.11 as prod
> ADD velero /usr/local/bin/         <-----------  add this line
> RUN apk update && \
> ```
> 
>     1. Modify the Makefile for test
> 
> 
> ```
> image: ## Build and push image
> 	docker build -t ${IMG}:latest -f ${DOCKER_DIR}/Dockerfile .    <------------  just retain this line
> ```
> 
> ### **Step 3**
> 
>     1. Enter into ./velero-dashboard
> 
>     2. Commit command `make image`
> 
>     3. After build image successfully use `docker images` to check it
> 
>     4. Export the image to local `docker save -o velero-dashboard.tar klinux/velero-dashboard:latest`
>        or push this image to your registry which kubernetes use.
> 
> 
> ### **Step 4**
> 
>     1. Modify the deployment file to assgin a right `serviceAccount ` in /velero-dashboard/utils/kubernetes/velero-dashboard-dep.yaml
> 
> 
> ```
>     spec:
>       serviceAccount: velero          <-----------  add this line
>       containers:
> ```
> 
>     1. (optional) Modify the svc file to enable NodePort.
> 
>     2. `kubectl apply -f .`
> 
>     3. It works.

**Comment by klinux** [comment]
I'm sorry, my bad, no intentional close the issue :),

Thank you for reply the issue, well, I will fix the project, can you submit a PR with the fix? I'm back with the project and update the things.

**Comment by drummerglen** [comment]
@klinux Sure, I‘ve been submited
